---
# Example playbook for ansible-role-deploy-vms
# ansible-playbook -i inventory/ansible-vm.yml playbooks/ansible-playbooks-deploy-vms/deploy_vms_prod.yml

# ===========================================================================
# Deploy VMs to a vCenter server
# ===========================================================================
- name: Deploy VMs
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  module_defaults:
    group/vmware:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: false
  tags: play_deploy_vms

  vars_files:
    # Ansible vault with all required passwords
    - "../../credentials.yml"

  roles:
    - { role: jedimt.deploy_vms,
        ansible_password: "{{ vault_ansible_password }}",

        # vCenter datacenter to deploy VMs to
        vcenter_datacenter: 'SantaClara',

        # Folder where the VMs should be deployed
        vcenter_folder: '/{{ vcenter_datacenter }}/vm/Ansible',

        # vCenter cluster to use
        vcenter_cluster: 'Production',

        # vCenter IP or FQDN
        vcenter_hostname: 'tmevcsa.sc0.nebulon.com',

        # The VM network name to attach to the VM
        guest_network: 'VM Network'
    }
