---
# Requirements file for ansible-playbooks-nebulon repo. Used for testing purposes

roles:
  - name: jedimt.ansible_role_apt_disable_background_tasks
  - name: jedimt.ansible_role_authorized_keys
  - name: jedimt.ansible_role_clone_template
  - name: jedimt.ansible_role_cloud_init
  - name: jedimt.ansible_role_customize_vms
  - name: jedimt.ansible_role_deploy_vms
  - name: jedimt.ansible_role_dualhome_routing
  - name: jedimt.ansible_role_golang_install
  - name: jedimt.ansible_role_haproxy
  - name: jedimt.ansible_role_helm_install
  - name: jedimt.ansible_role_kadalu
  - name: jedimt.ansible_role_kubernetes_create_cluster
  - name: jedimt.ansible_role_kubernetes_join_nodes
  - name: jedimt.ansible_role_kubernetes_kube_prometheus
  - name: jedimt.ansible_role_kubernetes_metallb
  - name: jedimt.ansible_role_kubernetes_network_plugin
  - name: jedimt.ansible_role_kubernetes_nginx_ingress
  - name: jedimt.ansible_role_kubernetes_prep
  - name: jedimt.ansible_role_linux_add_scsi_dev
  - name: jedimt.ansible_role_mongodb_install
  - name: jedimt.ansible_role_nebulon_create_npod
  - name: jedimt.ansible_role_nebulon_csi_install
  - name: jedimt.ansible_role_nebulon_manage_volumes
  - name: jedimt.ansible_role_network_setup
  - name: jedimt.ansible_role_ssh_update_known_hosts
  - name: jedimt.ansible_role_vcenter_ovf
  - name: jedimt.ansible_role_vim
  - name: jedimt.ansible_role_vmware_config_file
  - name: jedimt.ansible_role_vmware_csi_deploy
  - name: jedimt.ansible_role_vmware_customize_esxi
  - name: jedimt.ansible_role_vmware_vcsa_customization
  - name: jedimt.ansible_role_vmware_vcsa_embedded_install
  - name: jedimt.ansible_role_wordpress
