---
# ===========================================================================
# Manage Nebulon Volumes
# ===========================================================================

# Example invocation:
# ansible-playbook -i inventory/lenovo.yml playbooks/ansible-playbook-nebulon-volume/manage_nebulon_volumes.yml

- name: Manage Nebulon Volumes
  hosts: localhost
  connection: local
  tags: play_neb_vols
  gather_facts: false

  # module_defaults requires nebulon.nebulon_on version 1.2.1 or later
  module_defaults:
    group/nebulon.nebulon_on.nebulon:
      neb_username: "{{ vault_neb_username }}"
      neb_password: "{{ vault_neb_password }}"

  vars_files:
    # Ansible vault with all required passwords
    - "../../credentials.yml"
    # Ansible vault with all required serial numbers
    - "../../serials.yml"

  roles:
    - { role: jedimt.nebulon_manage_volumes,
        # State for all volumes (present|absent)
        volume_state: present,

        # Specify LUN export method (does not affect underlying volume)
        # (present|all) -> All nPod servers can access export
        # (host) -> Make export available to a single host. Requires host_uuid
        # (local) -> Make export available only to the local host that owns the volume
        # (absent) -> Remove the volume export
        export_type: local,

        # nPod name to use when managing volumes/exports
        npod_name: "nPod_Lenovo",

        # List of volumes to manage (create or remove)
        volumes: [
          {
            name: "volume1",
            size: 1000000000000,
            mirrored: true,
            owner_spu_serial: "{{ server_10_spu_serial }}",
            backup_spu_serial: "{{ server_11_spu_serial }}",
            state: "{{ volume_state }}"
          },
          {
            name: "volume2",
            size: 1000000000000,
            mirrored: true,
            owner_spu_serial: "{{ server_11_spu_serial }}",
            backup_spu_serial: "{{ server_10_spu_serial }}",
            state: "{{ volume_state }}"
          }
        ]
    }
