---
# Used this to smoke out what interfaces to use for netplan config for Kubernetes
# Example invocation:
# ansible-playbook -i inventory/lenovo.yml playbooks/ansible-playbook-utility/network_test_role.yml

- name: Test network setup role
  hosts: servers

  vars_files:
    - ../../credentials.yml

  roles:
    - { role: ansible-role-network_setup }
